// ============================================================================================
// LOCALHOST Deploy
// ============================================================================================
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by id
GET http://localhost:8080/contacts/63c2683c355744f60488f85f

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Dana",
    "lastName":"Kellet",
    "email":"dKellet@email.com",
    "favoriteColor":"Yellow",
    "birthday":"06/19/1970"
}

### PUT contact
PUT http://localhost:8080/contacts/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
    "firstName":"Robert",
    "lastName":"Whitefield",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/05/1992"
}

### re-PUT contact (put back the original entry)
PUT http://localhost:8080/contacts/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
    "firstName":"Daniel",
    "lastName":"Coonrod",
    "email":"danielmartz@gmail.com",
    "favoriteColor":"Black",
    "birthday":"10/09/1980"
}

### DELETE contact
DELETE http://localhost:8080/contacts/6220b775099269ff7b31ceab HTTP/1.1


// ============================================================================================
// PRODUCTION Deploy
// ============================================================================================
### Get all contacts
GET https://ejw-week02.onrender.com/contacts

### Get contact by id
GET https://ejw-week02.onrender.com/contacts/63c2683c355744f60488f85f

### Create contact
POST https://ejw-week02.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Dana",
    "lastName":"Kellet",
    "email":"dKellet@test.com",
    "favoriteColor":"Yellow",
    "birthday":"06/19/1970"
}

### PUT contact
PUT https://ejw-week02.onrender.com/contacts/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
    "firstName":"Robert",
    "lastName":"Whitefield",
    "email":"test@email.com",
    "favoriteColor":"Hazel",
    "birthday":"06/05/1992"
}

### re-PUT contact (put back the original entry)
PUT https://ejw-week02.onrender.com/contacts/63c2683c355744f60488f860 HTTP/1.1
content-type: application/json

{
    "firstName":"Daniel",
    "lastName":"Coonrod",
    "email":"danielmartz@gmail.com",
    "favoriteColor":"Black",
    "birthday":"10/09/1980"
}

### DELETE contact
DELETE https://ejw-week02.onrender.com/contacts/6220e34083149913680f9a64 HTTP/1.1